// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SunnyRides.Services.Database;

#nullable disable

namespace SunnyRides.Services.Migrations
{
    [DbContext(typeof(SunnyRidesDbContext))]
    [Migration("20260917124520_RazloziOtkazivanja")]
    partial class RazloziOtkazivanja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.BlokadaVozila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("KreiraoKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Razlog")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KreiraoKorisnikId");

                    b.HasIndex("VoziloId", "DatumOd", "DatumDo");

                    b.ToTable("BlokadaVozila", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Cjenovnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DnevnaTarifa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mnozilac")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ModelVozilaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PopustPrag1")
                        .HasColumnType("int");

                    b.Property<int>("PopustPrag2")
                        .HasColumnType("int");

                    b.Property<decimal>("PopustProcenat1")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PopustProcenat2")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SatnaTarifa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ModelVozilaId", "DatumOd", "DatumDo");

                    b.ToTable("Cjenovnik", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.DozvolaKategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KategorijaDozvoleId")
                        .HasColumnType("int");

                    b.Property<int>("VozackaDozvolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaDozvoleId");

                    b.HasIndex("VozackaDozvolaId", "KategorijaDozvoleId")
                        .IsUnique();

                    b.ToTable("DozvolaKategorija", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Skracenica")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Drzava", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.EvidencijaStete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumEvidentiranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvidentiraoKorisnikId")
                        .HasColumnType("int");

                    b.Property<decimal>("Iznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PrimopredajaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidentiraoKorisnikId");

                    b.HasIndex("PrimopredajaId")
                        .IsUnique();

                    b.ToTable("EvidencijaStete", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.FotografijaPrimopredaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PrimopredajaId")
                        .HasColumnType("int");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PutanjaThumbnail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PrimopredajaId");

                    b.ToTable("FotografijaPrimopredaje", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostanskiBroj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId", "Naziv")
                        .IsUnique();

                    b.ToTable("Grad", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.HistorijaPretrage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CijenaDo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CijenaOd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkaId")
                        .HasColumnType("int");

                    b.Property<int?>("TipVozilaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("TipVozilaId");

                    b.HasIndex("KorisnikId", "DatumVrijeme");

                    b.ToTable("HistorijaPretrage", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.HistorijaStatusaRezervacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IzvrsioKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Razlog")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusIz")
                        .HasColumnType("int");

                    b.Property<int>("StatusU")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IzvrsioKorisnikId");

                    b.HasIndex("RezervacijaId", "DatumVrijeme");

                    b.ToTable("HistorijaStatusaRezervacije", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.KategorijaDozvole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Oznaka")
                        .IsUnique();

                    b.ToTable("KategorijaDozvole", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.KodZaResetLozinke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Iskoristen")
                        .HasColumnType("bit");

                    b.Property<string>("KodHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId", "Iskoristen");

                    b.ToTable("KodZaResetLozinke", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<bool>("Blokiran")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PutanjaSlike")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.KorisnikRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDodjele")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("KorisnikId", "RoleId")
                        .IsUnique();

                    b.ToTable("KorisnikRole", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Marka", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.ModelVozila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KategorijaDozvoleId")
                        .HasColumnType("int");

                    b.Property<int>("Kubikaza")
                        .HasColumnType("int");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SnagaKw")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("TipGorivaId")
                        .HasColumnType("int");

                    b.Property<int>("TipVozilaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaDozvoleId");

                    b.HasIndex("TipGorivaId");

                    b.HasIndex("TipVozilaId");

                    b.HasIndex("MarkaId", "Naziv")
                        .IsUnique();

                    b.ToTable("ModelVozila", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Notifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Procitana")
                        .HasColumnType("bit");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.HasIndex("KorisnikId", "Procitana", "DatumKreiranja");

                    b.ToTable("Notifikacija", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivna")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PutanjaSlike")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Aktivna", "DatumObjave");

                    b.ToTable("Obavijest", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.ObradjeniWebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipEventa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderEventId")
                        .IsUnique();

                    b.ToTable("ObradjeniWebhookEvent", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.OpozvaniToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOpoziva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DatumIsteka");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("OpozvaniToken", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.PaketOsiguranja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoDanu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IznosUcesca")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("PaketOsiguranja", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumAzuriranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Iznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NaplaceniIznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderPaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderPaymentIntentId");

                    b.HasIndex("RezervacijaId")
                        .IsUnique()
                        .HasFilter("[Status] = 3");

                    b.ToTable("Placanje", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Poslovnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<double?>("Latituda")
                        .HasColumnType("float");

                    b.Property<double?>("Longituda")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RadnoVrijeme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Poslovnica", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.PravilaKategorije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KategorijaDozvoleId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxKubikaza")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxSnagaKw")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MinGodine")
                        .HasColumnType("int");

                    b.Property<int>("TipVozilaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipVozilaId");

                    b.HasIndex("KategorijaDozvoleId", "TipVozilaId")
                        .IsUnique();

                    b.ToTable("PravilaKategorije", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Primopredaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<int>("IzvrsioKorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraza")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NivoGoriva")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IzvrsioKorisnikId");

                    b.HasIndex("RezervacijaId", "Tip")
                        .IsUnique();

                    b.ToTable("Primopredaja", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.RazlogOtkazivanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TraziNapomenu")
                        .HasColumnType("bit");

                    b.Property<bool>("ZaAgenciju")
                        .HasColumnType("bit");

                    b.Property<bool>("ZaKlijenta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("RazlogOtkazivanja", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<bool>("Skrivena")
                        .HasColumnType("bit");

                    b.Property<int>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId")
                        .IsUnique();

                    b.HasIndex("KorisnikId", "RezervacijaId")
                        .IsUnique();

                    b.HasIndex("VoziloId", "Skrivena");

                    b.ToTable("Recenzija", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KreiraoKorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("PlacanjeId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderRefundId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Razlog")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KreiraoKorisnikId");

                    b.HasIndex("PlacanjeId");

                    b.ToTable("Refund", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Broj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumOtkazivanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DrziDo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("IznosDepozita")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IznosPopusta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("NapomenaOtkazivanja")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OtkazaoKorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("PaketOsiguranjaId")
                        .HasColumnType("int");

                    b.Property<int>("PoslovnicaId")
                        .HasColumnType("int");

                    b.Property<int?>("RazlogOtkazivanjaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupanIznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Broj")
                        .IsUnique();

                    b.HasIndex("OtkazaoKorisnikId");

                    b.HasIndex("PaketOsiguranjaId");

                    b.HasIndex("PoslovnicaId");

                    b.HasIndex("RazlogOtkazivanjaId");

                    b.HasIndex("KorisnikId", "VoziloId", "DatumOd")
                        .IsUnique();

                    b.HasIndex("VoziloId", "Status", "DatumOd", "DatumDo");

                    b.ToTable("Rezervacija", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.SlikaVozila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("JeGlavna")
                        .HasColumnType("bit");

                    b.Property<string>("Putanja")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PutanjaThumbnail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Redoslijed")
                        .HasColumnType("int");

                    b.Property<int>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoziloId", "Redoslijed");

                    b.ToTable("SlikaVozila", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.StanjeOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("PoslovnicaId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaOpremeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoslovnicaId");

                    b.HasIndex("VrstaOpremeId", "PoslovnicaId")
                        .IsUnique();

                    b.ToTable("StanjeOpreme", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.StavkaOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoJedinici")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Iznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaOpremeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VrstaOpremeId");

                    b.HasIndex("RezervacijaId", "VrstaOpremeId")
                        .IsUnique();

                    b.ToTable("StavkaOpreme", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.TipGoriva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("TipGoriva", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.TipVozila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("TipVozila", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.VozackaDozvola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojDozvole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumVerifikacije")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("PutanjaSlike")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazlogOdbijanja")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VerifikovaoKorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrojDozvole")
                        .IsUnique();

                    b.HasIndex("KorisnikId")
                        .IsUnique();

                    b.HasIndex("VerifikovaoKorisnikId");

                    b.ToTable("VozackaDozvola", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Vozilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DnevnaTarifa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<decimal>("IznosDepozita")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kilometraza")
                        .HasColumnType("int");

                    b.Property<int>("ModelVozilaId")
                        .HasColumnType("int");

                    b.Property<int>("PoslovnicaId")
                        .HasColumnType("int");

                    b.Property<string>("RegistarskaOznaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SatnaTarifa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ModelVozilaId");

                    b.HasIndex("PoslovnicaId");

                    b.HasIndex("RegistarskaOznaka")
                        .IsUnique();

                    b.ToTable("Vozilo", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.VrstaOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CijenaPoDanu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FiksnaCijena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("VrstaOpreme", (string)null);
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.BlokadaVozila", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "KreiraoKorisnik")
                        .WithMany()
                        .HasForeignKey("KreiraoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Vozilo", "Vozilo")
                        .WithMany("Blokade")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KreiraoKorisnik");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Cjenovnik", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.ModelVozila", "ModelVozila")
                        .WithMany("Cjenovnici")
                        .HasForeignKey("ModelVozilaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelVozila");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.DozvolaKategorija", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.KategorijaDozvole", "KategorijaDozvole")
                        .WithMany("DozvoleKategorije")
                        .HasForeignKey("KategorijaDozvoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.VozackaDozvola", "VozackaDozvola")
                        .WithMany("Kategorije")
                        .HasForeignKey("VozackaDozvolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategorijaDozvole");

                    b.Navigation("VozackaDozvola");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.EvidencijaStete", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "EvidentiraoKorisnik")
                        .WithMany()
                        .HasForeignKey("EvidentiraoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Primopredaja", "Primopredaja")
                        .WithOne("EvidencijaStete")
                        .HasForeignKey("SunnyRides.Services.Database.Entities.EvidencijaStete", "PrimopredajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvidentiraoKorisnik");

                    b.Navigation("Primopredaja");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.FotografijaPrimopredaje", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Primopredaja", "Primopredaja")
                        .WithMany("Fotografije")
                        .HasForeignKey("PrimopredajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Primopredaja");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Grad", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Drzava", "Drzava")
                        .WithMany("Gradovi")
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.HistorijaPretrage", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "Korisnik")
                        .WithMany("HistorijaPretraga")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Marka", "Marka")
                        .WithMany()
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunnyRides.Services.Database.Entities.TipVozila", "TipVozila")
                        .WithMany()
                        .HasForeignKey("TipVozilaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grad");

                    b.Navigation("Korisnik");

                    b.Navigation("Marka");

                    b.Navigation("TipVozila");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.HistorijaStatusaRezervacije", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "IzvrsioKorisnik")
                        .WithMany()
                        .HasForeignKey("IzvrsioKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunnyRides.Services.Database.Entities.Rezervacija", "Rezervacija")
                        .WithMany("HistorijaStatusa")
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IzvrsioKorisnik");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.KodZaResetLozinke", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.KorisnikRole", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "Korisnik")
                        .WithMany("KorisnikRole")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Role", "Role")
                        .WithMany("KorisnikRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.ModelVozila", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.KategorijaDozvole", "KategorijaDozvole")
                        .WithMany("Modeli")
                        .HasForeignKey("KategorijaDozvoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Marka", "Marka")
                        .WithMany("Modeli")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.TipGoriva", "TipGoriva")
                        .WithMany("Modeli")
                        .HasForeignKey("TipGorivaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.TipVozila", "TipVozila")
                        .WithMany("Modeli")
                        .HasForeignKey("TipVozilaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KategorijaDozvole");

                    b.Navigation("Marka");

                    b.Navigation("TipGoriva");

                    b.Navigation("TipVozila");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Notifikacija", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "Korisnik")
                        .WithMany("Notifikacije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Korisnik");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Placanje", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Rezervacija", "Rezervacija")
                        .WithMany("Placanja")
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Poslovnica", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Grad", "Grad")
                        .WithMany("Poslovnice")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.PravilaKategorije", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.KategorijaDozvole", "KategorijaDozvole")
                        .WithMany("PravilaKategorija")
                        .HasForeignKey("KategorijaDozvoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.TipVozila", "TipVozila")
                        .WithMany("PravilaKategorija")
                        .HasForeignKey("TipVozilaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KategorijaDozvole");

                    b.Navigation("TipVozila");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Primopredaja", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "IzvrsioKorisnik")
                        .WithMany()
                        .HasForeignKey("IzvrsioKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Rezervacija", "Rezervacija")
                        .WithMany("Primopredaje")
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IzvrsioKorisnik");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Recenzija", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "Korisnik")
                        .WithMany("Recenzije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Rezervacija", "Rezervacija")
                        .WithOne("Recenzija")
                        .HasForeignKey("SunnyRides.Services.Database.Entities.Recenzija", "RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Vozilo", "Vozilo")
                        .WithMany("Recenzije")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Rezervacija");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Refund", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "KreiraoKorisnik")
                        .WithMany()
                        .HasForeignKey("KreiraoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunnyRides.Services.Database.Entities.Placanje", "Placanje")
                        .WithMany("Refundi")
                        .HasForeignKey("PlacanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KreiraoKorisnik");

                    b.Navigation("Placanje");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Rezervacija", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "Korisnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "OtkazaoKorisnik")
                        .WithMany()
                        .HasForeignKey("OtkazaoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunnyRides.Services.Database.Entities.PaketOsiguranja", "PaketOsiguranja")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PaketOsiguranjaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunnyRides.Services.Database.Entities.Poslovnica", "Poslovnica")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.RazlogOtkazivanja", "RazlogOtkazivanja")
                        .WithMany("Rezervacije")
                        .HasForeignKey("RazlogOtkazivanjaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunnyRides.Services.Database.Entities.Vozilo", "Vozilo")
                        .WithMany("Rezervacije")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("OtkazaoKorisnik");

                    b.Navigation("PaketOsiguranja");

                    b.Navigation("Poslovnica");

                    b.Navigation("RazlogOtkazivanja");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.SlikaVozila", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Vozilo", "Vozilo")
                        .WithMany("Slike")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.StanjeOpreme", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Poslovnica", "Poslovnica")
                        .WithMany("StanjaOpreme")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.VrstaOpreme", "VrstaOpreme")
                        .WithMany("Stanja")
                        .HasForeignKey("VrstaOpremeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poslovnica");

                    b.Navigation("VrstaOpreme");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.StavkaOpreme", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Rezervacija", "Rezervacija")
                        .WithMany("StavkeOpreme")
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.VrstaOpreme", "VrstaOpreme")
                        .WithMany("Stavke")
                        .HasForeignKey("VrstaOpremeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rezervacija");

                    b.Navigation("VrstaOpreme");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.VozackaDozvola", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "Korisnik")
                        .WithOne("VozackaDozvola")
                        .HasForeignKey("SunnyRides.Services.Database.Entities.VozackaDozvola", "KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Korisnik", "VerifikovaoKorisnik")
                        .WithMany()
                        .HasForeignKey("VerifikovaoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Korisnik");

                    b.Navigation("VerifikovaoKorisnik");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Vozilo", b =>
                {
                    b.HasOne("SunnyRides.Services.Database.Entities.ModelVozila", "ModelVozila")
                        .WithMany("Vozila")
                        .HasForeignKey("ModelVozilaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SunnyRides.Services.Database.Entities.Poslovnica", "Poslovnica")
                        .WithMany("Vozila")
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelVozila");

                    b.Navigation("Poslovnica");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Drzava", b =>
                {
                    b.Navigation("Gradovi");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Grad", b =>
                {
                    b.Navigation("Poslovnice");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.KategorijaDozvole", b =>
                {
                    b.Navigation("DozvoleKategorije");

                    b.Navigation("Modeli");

                    b.Navigation("PravilaKategorija");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Korisnik", b =>
                {
                    b.Navigation("HistorijaPretraga");

                    b.Navigation("KorisnikRole");

                    b.Navigation("Notifikacije");

                    b.Navigation("Recenzije");

                    b.Navigation("Rezervacije");

                    b.Navigation("VozackaDozvola");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Marka", b =>
                {
                    b.Navigation("Modeli");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.ModelVozila", b =>
                {
                    b.Navigation("Cjenovnici");

                    b.Navigation("Vozila");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.PaketOsiguranja", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Placanje", b =>
                {
                    b.Navigation("Refundi");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Poslovnica", b =>
                {
                    b.Navigation("Rezervacije");

                    b.Navigation("StanjaOpreme");

                    b.Navigation("Vozila");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Primopredaja", b =>
                {
                    b.Navigation("EvidencijaStete");

                    b.Navigation("Fotografije");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.RazlogOtkazivanja", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Rezervacija", b =>
                {
                    b.Navigation("HistorijaStatusa");

                    b.Navigation("Placanja");

                    b.Navigation("Primopredaje");

                    b.Navigation("Recenzija");

                    b.Navigation("StavkeOpreme");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Role", b =>
                {
                    b.Navigation("KorisnikRole");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.TipGoriva", b =>
                {
                    b.Navigation("Modeli");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.TipVozila", b =>
                {
                    b.Navigation("Modeli");

                    b.Navigation("PravilaKategorija");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.VozackaDozvola", b =>
                {
                    b.Navigation("Kategorije");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.Vozilo", b =>
                {
                    b.Navigation("Blokade");

                    b.Navigation("Recenzije");

                    b.Navigation("Rezervacije");

                    b.Navigation("Slike");
                });

            modelBuilder.Entity("SunnyRides.Services.Database.Entities.VrstaOpreme", b =>
                {
                    b.Navigation("Stanja");

                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
